global:
  scrape_interval: 500ms
  evaluation_interval: 500ms

rule_files:
  - /etc/prometheus/alerts.yml

scrape_configs:
  - job_name: curtain-app
    metrics_path: /metrics
    static_configs:
      - targets:
          - app:5000
          - app2:5000
